const fs = require('fs')
const path = require('path')

// Cycle 127: the 3 cross-SDK parity suites (patent-vectors, cross-platform,
// cross-platform-canonical) statically import shared fixtures from the monorepo's
// sdks/shared-test-results/ (one level above this repo) — which is ABSENT in a
// standalone GitHub Actions checkout of this SDK alone, so they fail to load there.
// Gate them on the fixtures existing: run them in the monorepo (where the fixtures
// live + are generated by the self-test), skip them in a standalone CI checkout.
const sharedDir = path.resolve(__dirname, '../shared-test-results')
const sharedFixturesPresent =
  fs.existsSync(path.join(sharedDir, 'canonical-patent-vectors.json')) &&
  fs.existsSync(path.join(sharedDir, 'cross-platform-test-vectors.json')) &&
  fs.existsSync(path.join(sharedDir, 'javascript-results.json'))

module.exports = {
  roots: ['<rootDir>/tests'],
  collectCoverage: true,
  coverageDirectory: 'coverage',
  coverageReporters: ['json', 'lcov', 'text', 'clover'],
  testEnvironment: 'node',
  transform: {
    '^.+\\.js$': 'esbuild-jest'
  },
  transformIgnorePatterns: [
    '/node_modules/(?!(esmock|@noble))'
  ],
  testPathIgnorePatterns: sharedFixturesPresent
    ? ['/node_modules/']
    : [
      '/node_modules/',
      'tests/patent-vectors.test.js',
      'tests/cross-platform.test.js',
      'tests/cross-platform-canonical.test.js'
    ]
}
